num1 = int (input("Enter the first number : "))
num2 = int(input("Enter the second number : "))
result = (num1) + (num2)
print("the result is ",result)
result1=(num1) -(num2)
print("the result is ",result1)